### ISSUE TITLE
Leaking private chat ?

### ISSUE THREAD

**Issue by Trikolon** [Tallcraft/ChatReplay#4]
Detect if chat event is "private", for example mcmmo party chat.

**Comment by RoboMWM** [comment]
May be possible via checking if recipient size is less than online player size, but only works if there's other people online that are not in the party.

**Comment by Trikolon** [comment]
So we could softdepend on a bunch of popular plugins like McMMO and GP and use their APIs.

**Comment by Trikolon** [comment]
I've changed the chat event listener priority to monitor and it also checks for cancelled events now, this might be fixed now. Needs testing.
