### ISSUE TITLE
"Invalid viewSize. Can not be smaller than total buffer size"

### ISSUE THREAD

**Issue by Flipybitz** [Tallcraft/ChatReplay#6]
Running Paper Spigot API version 1.12.2-R0.1-SNAPSHOT

Gives me the error below, which only happened as I just now downloaded the updated version. Previous version works as expected without errors.

10:03:15 PM [INFO] [ChatReplay] Enabling ChatReplay v1.3.0
10:03:15 PM [SEVERE] Error occurred while enabling ChatReplay v1.3.0 (Is it up to date?)
10:03:15 PM java.lang.IllegalArgumentException: ChatReplay: Invalid viewSize. Can not be smaller than total buffer size
10:03:15 PM 	at com.tallcraft.chatreplay.ChatReplay.configureBuffer(ChatReplay.java:113) ~[?:?]
10:03:15 PM 	at com.tallcraft.chatreplay.ChatReplay.onEnable(ChatReplay.java:28) ~[?:?]
10:03:15 PM 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1339]
10:03:15 PM 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1339]
10:03:15 PM 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1339]
10:03:15 PM 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [patched_1.12.2.jar:git-Paper-1339]
10:03:15 PM 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [patched_1.12.2.jar:git-Paper-1339]
10:03:15 PM 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1339]
10:03:15 PM 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1339]
10:03:15 PM 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1339]
10:03:15 PM 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1339]
10:03:15 PM 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1339]
10:03:15 PM 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
10:03:15 PM [INFO] [ChatReplay] Disabling ChatReplay v1.3.0

**Comment by Trikolon** [comment]
Rename your old configuration file and let the plugin generate a new one. I don't have any logic to update configuration files to newer versions yet and thus you're possibly missing some options.

**Comment by Trikolon** [comment]
I've published an update which should fix this without needing to re-generate the config:
https://github.com/Tallcraft/ChatReplay/releases/tag/v1.3.1
Please let me know if it works for you.

**Comment by Trikolon** [comment]
Also, you have to make sure that your `bufferSize` in the config is at least `viewSize` or higher.

**Comment by Flipybitz** [comment]
Yes after updating the plugin again the error went away, deleted all config files to be sure also. Working great now! :+1:

**Comment by Trikolon** [comment]
Great! Thank you for reporting the issue.
