### ISSUE TITLE
Also store broadcasted messages

### ISSUE THREAD

**Issue by RoboMWM** [Tallcraft/ChatReplay#7]
I've been interested in using/making a plugin like this, but I'd also like to store messages from chat bridges like IRC, Slack, discord, etc. that I relay to the server. Easiest way would probably via listening to the BroadcastMessageEvent (which may only be in Paper's API?)

**Comment by Trikolon** [comment]
That's a good idea!
I'm also using a discord bridge on some of my servers and I think it would be very useful.

Is it possible to maintain spigot support while also supporting the paper API? I would like to avoid distributing two separate binaries.

**Comment by Trikolon** [comment]
I might have a look at this over the next few days, or do you want to submit a PR?

**Comment by Trikolon** [comment]
I've asked the developers of DiscordSRV. Unfortunately it does not trigger any events outside of their API. We'd have to use that.

**Comment by RoboMWM** [comment]
Oh, do they not use broadcastMessage and instead just player#sendMessage in a loop?

**Comment by Trikolon** [comment]
I've implemented support for DiscordSRV: https://github.com/Tallcraft/ChatReplay/blob/dev/src/main/java/com/tallcraft/chatreplay/DiscordSRVListener.java
For now it only records the main channel.
